<div class="share-button-container"><share-button class="btn btn-primary btn-lg">Share this <i class="fa fa-share"></i></share-button></div>
<script>
loadScript('share-button');
loadScript(function(){
	new ShareButton({
		ui: {
        buttonText: 'Share this post <i class="icon icon-share"></i>',
        collision: false
      },
		networks: {
			facebook: {
				app_id: "1087913877916081"
			},
		}
	});
});
</script>