fragment pledgeFields on AllPledgesPublicsEdge {
  node {
    rankByPledgeType
        fullName
        pledgeStart
        pledgeEnd
        pledgePercentage
        pledgeType
        anonymous
        withdrawn
        inactive
  }
}

query stats {
  Pledgers: allAllPledgesPublics(
    condition: { pledgeType: GIVING_WHAT_WE_CAN }
  ) {
    edges {
      ...pledgeFields
    }
  }
  TryGivers: allAllPledgesPublics(condition: { pledgeType: TRY_GIVING }) {
    edges {
      ...pledgeFields
    }
  }
  ProjectedDonations: getTotalProjectedDonations {
    projectedDonationsTotal
    projectedIncomeTotal
    numPledges
  }
  TotalGWWCDonations: getTotalGwwcDonations
  TotalCompletionPayments: getTotalCompletionPayments
  GWWCMemberCountries: getGwwcMemberCountries {
    edges {
      node {
        countryCode
        count
      }
    }
  }
}
