<div class="row">
	<div class="col-xs-12">
		<div class="alert alert-info">
			<strong><i class="fa fa-info"></i> Just so you know...</strong> We're in the process of updating all of our research pages. While we're doing this, some content may be temporarily missing or incomplete. If you have any questions, please email the research team at <a href="mailto:research@givingwhatwecan.org">research@givingwhatwecan.org</a>. Sorry for any inconvenience!
		</div>
	</div>
</div>