<div class="row">
	<div class="col-xs-12">
		<div class="alert alert-warning">
      <h4>Notice about research</h4>
			<p>Giving What We Can no longer conducts our own research into charities and cause areas. Instead, we're relying on the work of organisations including <a href='https://www.povertyactionlab.org/'>J-PAL</a>, <a href='http://www.givewell.org/'>GiveWell</a>, and the <a href='http://www.openphilanthropy.org/'>Open Philanthropy Project</a>, which are in a better position to provide more comprehensive research coverage.</p>
      <p>These research reports represent our thinking as of late 2016, and much of the information will be relevant for making decisions about how to donate as effectively as possible. However we are not updating them and the information may therefore be out of date.</p>
		</div>
	</div>
</div>
