<div class="call-to-action">
	<div class="row">
		<div class="col-xs-12">
			<h3>{{callToAction|default("What are you waiting for?")}}</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-4 sm-offset-1">
			<a href="/get-involved/join-us" class="btn btn-primary">Become a member</a>
		</div>
		<div class="col-sm-4 sm-offset-1">
			<a href="/get-involved/try-giving" class="btn btn-secondary">Learn about Try Giving</a>
		</div>
	</div>
</div>
